### ISSUE TITLE
Create branches per directory

### ISSUE THREAD

**Issue by patrickmj** [NEU-DSG/wwp-public-code-share#9]

**Comment by sydb** [comment]
First step (nuking branch _develop_) has just been done. Thus if you have a local copy of this repository you should issue `git fetch --all --prune` to get rid of the now obsolete tracking branch. (Found that on [Stackoverflow](https://stackoverflow.com/questions/2003505/how-do-i-delete-a-git-branch-both-locally-and-remotely).)

**Comment by sydb** [comment]
Done, w/ thanks to @amclark42. (We bashed our heads against the screen for awhile to get the `git` syntax right.)
Note that there is currently only one branch for `miscellaneous`, which may end up containing lots of various small utilities. We may (someday) want a separate branch for each of those.
